// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseSingleSelect: typeof import('./src/components/BaseSingleSelect.vue')['default']
    BaseTab: typeof import('./src/components/BaseTab.vue')['default']
    FooTab: typeof import('./src/components/tabs/fooTab.vue')['default']
    HelloPinia: typeof import('./src/components/HelloPinia.vue')['default']
    HogeTab: typeof import('./src/components/tabs/hogeTab.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
  }
}
