/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApiKeyTextfield: typeof import('./src/components/ApiKeyTextfield.vue')['default']
    BaseSingleSelect: typeof import('./src/components/BaseSingleSelect.vue')['default']
    BaseTab: typeof import('./src/components/BaseTab.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
  }
}
