// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloPinia: typeof import('./src/components/HelloPinia.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VHelloPinia: typeof import('vuetify/lib')['VHelloPinia']
    VListGroup: typeof import('vuetify/lib')['VListGroup']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemGroup: typeof import('vuetify/lib')['VListItemGroup']
    VListItemIcon: typeof import('vuetify/lib')['VListItemIcon']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VRow: typeof import('vuetify/lib')['VRow']
  }
}
