import { TestData } from "./store/master";

export const tableItems: Array<TestData> = [
  {
    guid: "1",
    name: "河童",
    furigana: "カッパ",
    type: "妖怪",
    region: "日本全国",
    description: "水辺に住む亀のような姿をした小人で、頭の上に皿がある",
  },
  {
    guid: "2",
    name: "狸",
    furigana: "タヌキ",
    type: "妖怪",
    region: "日本全国",
    description: "犬や狸を思わせる姿の動物で、化ける能力があるとされる",
  },
  {
    guid: "3",
    name: "鵺",
    furigana: "ヌエ",
    type: "妖怪",
    region: "日本全国",
    description:
      "さまざまな動物の部位が組み合わさった姿で、夜に叫ぶことで人々を恐れさせる",
  },
  {
    guid: "4",
    name: "雪女",
    furigana: "ゆきおんな",
    type: "妖怪",
    region: "日本全国",
    description: "雪の中に現れる美しい女性で、冷気を操る能力があるとされる",
  },
  {
    guid: "5",
    name: "龍",
    furigana: "りゅう",
    type: "神話上の生き物",
    region: "日本全国",
    description: "空を飛び、雨や雷を操る能力があるとされる大蛇の姿をした生き物",
  },
  {
    guid: "6",
    name: "八岐大蛇",
    furigana: "やまたのおろち",
    type: "神話上の生き物",
    region: "日本全国",
    description:
      "八つの頭と八つの尾を持つ巨大な蛇で、スサノオノミコトによって倒された",
  },
  {
    guid: "7",
    name: "鳳凰",
    furigana: "ほうおう",
    type: "神話上の生き物",
    region: "日本・中国",
    description: "美しい羽根を持ち、不死で再生する力を持つとされる神秘的な鳥",
  },
  {
    guid: "8",
    name: "鯨魚",
    furigana: "けげい",
    type: "神話上の生き物",
    region: "日本全国",
    description: "海の怪物であり、船を襲ったり、海を荒らす力を持つとされる",
  },
  {
    guid: "9",
    name: "金太郎",
    furigana: "きんたろう",
    type: "伝説の英雄",
    region: "日本全国",
    description:
      "非常に強い力を持ち、熊と戦ったり木を折ったりすることができる子供",
  },
  {
    guid: "10",
    name: "騒々しい村",
    furigana: "さわさわしいむら",
    type: "伝説の場所",
    region: "日本全国",
    description: "妖怪や神話上の生き物たちが住むとされる不思議な村",
  },
];

export const scheduleItems = [
  {
    id: 1,
    memberId: "1",
    title: "会議",
    date: "2023-03-22",
    startTime: "2023-03-01T14:00:00:",
    endTime: "2023-03-01T16:00:00",
    location: "会議室A",
    description: "新製品の戦略について議論する",
    importance: 3,
  },
  {
    id: 2,
    memberId: "1",
    title: "健康診断",
    date: "2023-04-05",
    startTime: "2023-03-01T09:00:00",
    endTime: "2023-03-01T11:00:00",
    location: "会社の保健室",
    description: "定期的な健康診断を受ける",
    importance: 2,
  },
  {
    id: 3,
    memberId: "1",
    title: "デザインレビュー",
    date: "2023-03-25",
    startTime: "2023-03-01T13:00:00",
    endTime: "2023-03-01T15:00:00",
    location: "オンライン",
    description: "新しいWebサイトのデザイン案をレビューする",
    importance: 1,
  },
  {
    id: 4,
    memberId: "1",
    title: "懇親会",
    date: "2023-04-01",
    startTime: "2023-03-01T18:00:00",
    endTime: "2023-03-01T21:00:00",
    location: "レストランA",
    description: "部署の懇親を深める",
    importance: 2,
  },
  {
    id: 5,
    memberId: "1",
    title: "プレゼンテーション",
    date: "2023-04-10",
    startTime: "2023-03-01T10:00:00",
    endTime: "2023-03-01T12:00:00",
    location: "会議室B",
    description: "新しい製品のプレゼンテーションを行う",
    importance: 3,
  },
  {
    id: 2,
    memberId: "2",
    title: "面接",
    date: "2023-04-01",
    startTime: "2023-04-01T10:00:00",
    endTime: "2023-04-01T11:30:00",
    location: "会議室B",
    description: "採用担当者との面接",
    importance: 4,
  },
  {
    id: 3,
    memberId: "2",
    title: "研修",
    date: "2023-05-10",
    startTime: "2023-05-10T11:30:00",
    endTime: "2023-05-10T12:00:00",
    location: "研修室C",
    description: "新人研修",
    importance: 2,
  },
  {
    id: 4,
    memberId: "2",
    title: "取引先訪問",
    date: "2023-06-20",
    startTime: "2023-06-20T13:00:00",
    endTime: "2023-06-20T16:00:00",
    location: "取引先オフィス",
    description: "新製品の提案",
    importance: 5,
  },
  {
    id: 5,
    memberId: "2",
    title: "プロジェクトミーティング",
    date: "2023-07-01",
    startTime: "2023-07-01T15:00:00",
    endTime: "2023-07-01T18:00:00",
    location: "会議室D",
    description: "プロジェクトの進捗確認",
    importance: 3,
  },
  {
    id: 6,
    memberId: "2",
    title: "打ち合わせ",
    date: "2023-08-05",
    startTime: "2023-08-05T11:00:00",
    endTime: "2023-08-05T12:30:00",
    location: "会議室E",
    description: "プロジェクト関連の打ち合わせ",
    importance: 4,
  },
];

export const services = [
  { text: "NHK総合1", value: "g1" },
  { text: "NHK総合2", value: "g2" },
  { text: "NHK Eテレ1", value: "e1" },
  { text: "NHKワンセグ2", value: "e4" },
  { text: "NHK BS1", value: "s1" },
  { text: "NHK BSプレミアム", value: "s5" },
  { text: "NHKラジオ第1", value: "r1" },
  { text: "NHKラジオ第2", value: "r2" },
  { text: "NHK FM", value: "r3" },
];

export const areas = [
  { text: "札幌", value: "010" },
  { text: "函館", value: "011" },
  { text: "旭川", value: "012" },
  { text: "帯広", value: "013" },
  { text: "釧路", value: "014" },
  { text: "北見", value: "015" },
  { text: "室蘭", value: "016" },
  { text: "青森", value: "020" },
  { text: "盛岡", value: "030" },
  { text: "仙台", value: "040" },
  { text: "秋田", value: "050" },
  { text: "山形", value: "060" },
  { text: "福島", value: "070" },
  { text: "水戸", value: "080" },
  { text: "宇都宮", value: "090" },
  { text: "前橋", value: "100" },
  { text: "さいたま", value: "110" },
  { text: "千葉", value: "120" },
  { text: "東京", value: "130" },
  { text: "横浜", value: "140" },
  { text: "新潟", value: "150" },
  { text: "富山", value: "160" },
  { text: "金沢", value: "170" },
  { text: "福井", value: "180" },
  { text: "甲府", value: "190" },
  { text: "長野", value: "200" },
  { text: "岐阜", value: "210" },
  { text: "静岡", value: "220" },
  { text: "名古屋", value: "230" },
  { text: "津", value: "240" },
  { text: "大津", value: "250" },
  { text: "京都", value: "260" },
  { text: "大阪", value: "270" },
  { text: "神戸", value: "280" },
  { text: "奈良", value: "290" },
  { text: "和歌山", value: "300" },
  { text: "鳥取", value: "310" },
  { text: "松江", value: "320" },
  { text: "岡山", value: "330" },
  { text: "広島", value: "340" },
  { text: "山口", value: "350" },
  { text: "徳島", value: "360" },
  { text: "高松", value: "370" },
  { text: "松山", value: "380" },
  { text: "高知", value: "390" },
  { text: "福岡", value: "400" },
  { text: "北九州", value: "401" },
  { text: "佐賀", value: "410" },
  { text: "長崎", value: "420" },
  { text: "熊本", value: "430" },
  { text: "大分", value: "440" },
  { text: "宮崎", value: "450" },
  { text: "鹿児島", value: "460" },
  { text: "沖縄", value: "470" },
];
